repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # file type specific checks
      - id: check-yaml # verifies syntax of yaml files
      - id: check-json # verifies syntax of json files
      - id: pretty-format-json # fixes indentation of json files
        args: [ "--autofix", "--no-sort-keys" ]
      - id: check-toml # verifies syntax of toml files
      - id: check-executables-have-shebangs # verifies non-binary executables have shebang
      # general files
      - id: end-of-file-fixer # makes sure files end in a newline and only a newline.
        exclude: 'docs\/source\/examples\/metabase_token'
      - id: trailing-whitespace # trims trailing whitespace.
      - id: check-case-conflict # check for files that would conflict on a case-insensitive filesystem
      - id: detect-private-key # checks for the existence of private keys
      - id: check-added-large-files # prevent giant files from being committed
        args: [ "--maxkb=2048" ]
      # python checks
      - id: name-tests-test # verifies that test files are named correctly
        args: [ "--pytest-test-first" ]
        exclude: 'tests\/(helpers|setup_metabase).py'
      - id: check-docstring-first # checks for code before the docstring
      - id: debug-statements # check for debugger imports and breakpoint calls in python source
      # git checks
      - id: no-commit-to-branch # protect specific branches from direct checkins
        args: [ "--branch", "main" ]
        stages: [ pre-commit ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
